title: Neuroscience Deadlines # (Maintained by @abhshkdz)
# email: abhshkdz@vt.edu
description: Countdowns to top neuroscience (& related fields) conference deadlines
author: T. Bryn Grey

domain: "neuro-deadlines.tbryngrey.com"
baseurl: ""

twitter_username: tbryngrey
twitter_hashtag: neuroscience
github_username: tbryn
github_repo: neuro-deadlines

markdown: kramdown
ga_id: UA-36274081-2
